---
- block:
  - name: percona repository installed (CentOS/RHEL)
    yum:
      name: https://repo.percona.com/yum/percona-release-latest.noarch.rpm
      disable_gpg_check: yes

  - name: percona-release
    command: percona-release setup -y ps80

  - name: percona 8.0 installed (CentOS/RHEL)
    package:
      name:
        - Percona-Server-server
        - Percona-Server-client
        - Percona-Server-shared
        - Percona-Server-devel
      state: latest

  - name: python-PyMySQL installed (CentOS/RHEL 7 or 6)
    package:
      name:
        - MySQL-python
      state: latest
    when: ansible_distribution_major_version is version('7', '<=')

  - name: python-PyMySQL installed (CentOS/RHEL 8)
    package:
      name:
        - python3-PyMySQL
      state: latest
    when: ansible_distribution_major_version is version('8', '>=')

  when: ansible_os_family == 'RedHat'

- block:
  - name: percona-release repository installed (Debian)
    apt:
      deb: "https://repo.percona.com/apt/percona-release_latest.{{ ansible_distribution_release }}_all.deb"

  - name: percona-release
    command: percona-release enable-only ps-80 release

  - name: apt-get update
    apt:
      update_cache: yes

  - name: percona 8.0 installed (Debian)
    package:
      name:
        - percona-server-server
        - percona-server-client
        - percona-server-common
        - libperconaserverclient20-dev
        - python-mysqldb
      state: latest
  when: ansible_os_family == 'Debian'
