---
- name: openssl installed
  yum: name={{ item }} state=latest
  with_items:
    - openssl
    - openssl-devel
    - mod_ssl

- stat: path=/etc/pki/tls/{{ HOSTNAME }}
  register: is_ssl_path
- name: mkdir ssl
  file: path=/etc/pki/tls/{{ HOSTNAME }} state=directory owner=root
  when: not is_ssl_path.stat.exists

- name: generate a key
  shell: openssl genrsa -out /etc/pki/tls/{{ HOSTNAME }}/{{ HOSTNAME }}.key 2048

- name: Generate a certificate
  shell: openssl req -new -x509 -key /etc/pki/tls/{{ HOSTNAME }}/{{ HOSTNAME }}.key -out /etc/pki/tls/{{ HOSTNAME }}/{{ HOSTNAME }}.cert -days 3650 -subj /CN={{ HOSTNAME }}

- stat: path=/etc/httpd/conf.d/ssl.conf
  register: is_ssl_conf
- name: delete ssl.conf
  file: path=/etc/httpd/conf.d/ssl.conf state=absent
  when: is_ssl_conf.stat.exists
