---
- name: stat /tmp/openssl-{{ openssl_full_version }}
  stat:
    path: /tmp/openssl-{{ openssl_full_version }}
  register: is_tmp_openssl_dir

- name: include task
  include: install.yml
  when: not is_tmp_openssl_dir.stat.exists

- name: include task
  include: pki.yml
